from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Protocol, runtime_checkable

from app.domain.enums import ProjectStatus, RiskSeverity


@runtime_checkable
class IUserRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100, sort_by: str | None = None, sort_desc: bool = False, filters: dict[str, Any] | None = None) -> list[Any]: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def count(self, filters: dict[str, Any] | None = None) -> int: ...
    async def get_by_email(self, email: str) -> Any | None: ...
    async def get_by_username(self, username: str) -> Any | None: ...
    async def get_active_users(self) -> list[Any]: ...
    async def search(self, query: str) -> list[Any]: ...


@runtime_checkable
class IProjectRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100, sort_by: str | None = None, sort_desc: bool = False, filters: dict[str, Any] | None = None) -> list[Any]: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def count(self, filters: dict[str, Any] | None = None) -> int: ...
    async def get_by_code(self, code: str) -> Any | None: ...
    async def get_by_status(self, status: ProjectStatus) -> list[Any]: ...
    async def get_delayed_projects(self) -> list[Any]: ...
    async def search(self, query: str, filters: dict[str, Any] | None = None) -> tuple[list[Any], int]: ...
    async def get_dashboard_stats(self) -> dict[str, Any]: ...


@runtime_checkable
class IProjectPartRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100, sort_by: str | None = None, sort_desc: bool = False, filters: dict[str, Any] | None = None) -> list[Any]: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def count(self, filters: dict[str, Any] | None = None) -> int: ...
    async def get_by_project(self, project_id: uuid.UUID) -> list[Any]: ...
    async def get_by_part_number(self, part_number: str) -> Any | None: ...
    async def search(self, query: str, project_id: uuid.UUID | None = None) -> list[Any]: ...


@runtime_checkable
class ISupplierRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100, sort_by: str | None = None, sort_desc: bool = False, filters: dict[str, Any] | None = None) -> list[Any]: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def count(self, filters: dict[str, Any] | None = None) -> int: ...
    async def get_by_code(self, code: str) -> Any | None: ...
    async def search(self, query: str, filters: dict[str, Any] | None = None) -> tuple[list[Any], int]: ...
    async def get_top_suppliers(self, limit: int = 5) -> list[Any]: ...


@runtime_checkable
class ICapacityAssessmentRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100, sort_by: str | None = None, sort_desc: bool = False, filters: dict[str, Any] | None = None) -> list[Any]: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def count(self, filters: dict[str, Any] | None = None) -> int: ...
    async def get_by_part(self, project_part_id: uuid.UUID) -> list[Any]: ...
    async def get_by_supplier(self, supplier_id: uuid.UUID) -> list[Any]: ...
    async def get_by_month(self, year: int, month: int) -> list[Any]: ...
    async def get_coverage_stats(self) -> dict[str, Any]: ...


@runtime_checkable
class IRiskRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100, sort_by: str | None = None, sort_desc: bool = False, filters: dict[str, Any] | None = None) -> list[Any]: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def count(self, filters: dict[str, Any] | None = None) -> int: ...
    async def get_by_part(self, project_part_id: uuid.UUID) -> list[Any]: ...
    async def get_open_risks(self) -> list[Any]: ...
    async def get_by_severity(self, severity: RiskSeverity) -> list[Any]: ...
    async def get_risk_distribution(self) -> dict[str, Any]: ...


@runtime_checkable
class IDocumentRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100, sort_by: str | None = None, sort_desc: bool = False, filters: dict[str, Any] | None = None) -> list[Any]: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def count(self, filters: dict[str, Any] | None = None) -> int: ...
    async def get_by_project(self, project_id: uuid.UUID) -> list[Any]: ...
    async def get_by_part(self, project_part_id: uuid.UUID) -> list[Any]: ...


@runtime_checkable
class INotificationRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100, sort_by: str | None = None, sort_desc: bool = False, filters: dict[str, Any] | None = None) -> list[Any]: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def count(self, filters: dict[str, Any] | None = None) -> int: ...
    async def get_by_user(self, user_id: uuid.UUID) -> list[Any]: ...
    async def get_unread_count(self, user_id: uuid.UUID) -> int: ...
    async def mark_as_read(self, notification_id: uuid.UUID) -> bool: ...
    async def mark_all_as_read(self, user_id: uuid.UUID) -> int: ...


@runtime_checkable
class IActivityLogRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100, sort_by: str | None = None, sort_desc: bool = False, filters: dict[str, Any] | None = None) -> list[Any]: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def count(self, filters: dict[str, Any] | None = None) -> int: ...
    async def get_by_user(self, user_id: uuid.UUID) -> list[Any]: ...
    async def get_by_resource(self, resource_type: str, resource_id: uuid.UUID) -> list[Any]: ...
    async def get_recent(self, limit: int = 20) -> list[Any]: ...


@runtime_checkable
class IPasswordResetTokenRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def get_by_token(self, token: str) -> Any | None: ...


@runtime_checkable
class ISessionRepository(Protocol):
    async def get(self, id: uuid.UUID) -> Any | None: ...
    async def create(self, data: dict[str, Any] | Any) -> Any: ...
    async def update(self, id: uuid.UUID, data: dict[str, Any] | Any) -> Any | None: ...
    async def delete(self, id: uuid.UUID) -> bool: ...
    async def get_by_refresh_token(self, refresh_token: str) -> Any | None: ...
    async def revoke_user_sessions(self, user_id: uuid.UUID) -> int: ...
