from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class IAuthService(Protocol):
    async def login(self, email: str, password: str, ip_address: str | None = None, user_agent: str | None = None) -> Any: ...
    async def logout(self, refresh_token: str) -> bool: ...
    async def refresh(self, refresh_token: str) -> Any: ...
    async def change_password(self, user_id: Any, old_password: str, new_password: str) -> bool: ...
    async def request_password_reset(self, email: str) -> bool: ...
    async def reset_password(self, token: str, new_password: str) -> bool: ...
    async def register(self, data: Any) -> Any: ...


@runtime_checkable
class IFileStorageService(Protocol):
    async def save_file(self, file: Any, subdirectory: str = "") -> str: ...
    async def delete_file(self, file_path: str) -> bool: ...
    async def get_file_path(self, file_path: str) -> str: ...


@runtime_checkable
class IEmailService(Protocol):
    async def send_email(self, to: str, subject: str, body: str, html: bool = False) -> bool: ...
    async def send_password_reset(self, email: str, token: str) -> bool: ...
    async def send_notification(self, user_email: str, title: str, message: str) -> bool: ...


@runtime_checkable
class ICacheService(Protocol):
    async def get(self, key: str) -> Any | None: ...
    async def set(self, key: str, value: Any, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> bool: ...
    async def clear(self) -> None: ...


@runtime_checkable
class IUnitOfWork(Protocol):
    @property
    def users(self) -> Any: ...
    @property
    def projects(self) -> Any: ...
    @property
    def project_parts(self) -> Any: ...
    @property
    def suppliers(self) -> Any: ...
    @property
    def capacity_assessments(self) -> Any: ...
    @property
    def risks(self) -> Any: ...
    @property
    def documents(self) -> Any: ...
    @property
    def notifications(self) -> Any: ...
    @property
    def activity_logs(self) -> Any: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
