"""initial_schema

Revision ID: c50b87a1d473
Revises: 
Create Date: 2026-08-28 13:12:47.902849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50b87a1d473'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'template_id',
               existing_type=sa.TEXT(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('projects', 'template_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('projects', 'data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('projects', 'template_version',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'template_id',
               existing_type=sa.Uuid(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
